### ISSUE TITLE
Dokumentation Datenbank

### ISSUE THREAD

**Issue by KaiserKDA** [HorstVonMorgen/carpool#1]
Wir benötigen eine Dokumentation zur Datenbank.

- Tabellennamen
- Felder mit Datentypen
- Benötigte Sichten

**Comment by HorstVonMorgen** [comment]
Die Tabelle für Reservierungen/Ausleihen fehlt noch.

> CREATE TABLE IF NOT EXISTS `kfz` (
  `plate` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `typ` int(11) NOT NULL,
  `number` tinytext COLLATE utf8_unicode_ci NOT NULL,
  `hu` date NOT NULL,
  `color` tinytext COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`plate`),
  UNIQUE KEY `plate` (`plate`),
  KEY `typ` (`typ`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

>CREATE TABLE IF NOT EXISTS `ma` (
  `number` int(11) NOT NULL,
  `fname` tinytext COLLATE utf8_unicode_ci NOT NULL,
  `lname` tinytext COLLATE utf8_unicode_ci NOT NULL,
  `license` int(11) NOT NULL,
  `birthdate` date NOT NULL,
  `department` tinytext COLLATE utf8_unicode_ci NOT NULL,
  UNIQUE KEY `number` (`number`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

>CREATE TABLE IF NOT EXISTS `typ` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `brand` tinytext COLLATE utf8_unicode_ci NOT NULL,
  `model` tinytext COLLATE utf8_unicode_ci NOT NULL,
  `motor` tinytext COLLATE utf8_unicode_ci NOT NULL,
  `code` tinytext COLLATE utf8_unicode_ci NOT NULL,
  `doors` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=0 ;

**Comment by HorstVonMorgen** [comment]
## Tabelle: kfz

Feld| Typ
--- | ---
plate |varchar(255)
typ|int(11)
number|tinytext	
hu|date	
color|tinytext	
## Tabelle: ma
Feld| Typ
--- | ---
number|int(11)
fname|tinytext	
lname|tinytext
license|int(11)
birthdate|date
department|tinytext
## Tabelle: typ
Feld| Typ
--- | ---
id|int(11)
brand|tinytext
model|tinytext
motor|tinytext
code|tinytext
doors|int(11)

**Comment by HorstVonMorgen** [comment]
https://github.com/HorstVonMorgen/carpool/wiki/2.-Datenbank
