### ISSUE TITLE
Mockup Typen-Verwaltung

### ISSUE THREAD

**Issue by HorstVonMorgen** [HorstVonMorgen/carpool#3]
Kann es sein, dass das input-Feld für die Kraftstoffart fehlt?

**Comment by KaiserKDA** [comment]
Vielen Dank für deine Rückmeldung.
Ich habe das Feld hinzugefügt.

**Comment by KaiserKDA** [comment]
Bitte prüfe, ob jetzt alles passt. 
Danke

**Comment by HorstVonMorgen** [comment]
Sehr schön. Vielen Dank für die schnelle Bearbeitung. Ich hoffe weiterhin auf gute Zusammenarbeit.
