### ISSUE TITLE
Löschen eines Fahrzeugs

### ISSUE THREAD

**Issue by HorstVonMorgen** [HorstVonMorgen/carpool#4]
Wie gehen wir mit dem Löschen von Fahrzeugen um?

Aus der DB löschen und alle Reservierungen dazu ebenfalls löschen?
oder 
das Fahrzeug auf 'inaktiv' setzten. Alle Datensätze bleiben so bestehen, das Fahrzeug kann aber nicht mehr für eine Reservierung gewählt werden.

**Comment by HorstVonMorgen** [comment]
Löschen eines Modells ist auch kompliziert.

Man darf es erst löschen, wenn es keine Fahrzeuge zu diesem Modell gibt???

**Comment by KaiserKDA** [comment]
Zur Vermeidung von Inkonsistenzen in der Fahrzeug Historie ist es besser, wenn sowohl die Fahrzeuge und als auch die Fahrzeugtypen nur auf inaktiv gesetzt werden.
